## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have any question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

import pandas as pd

In [1]:
#!nvidia-smi

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu102


## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()` -> https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [13]:
## MATRIX

MATRIX = torch.tensor([[7,8],
                        [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor

TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6]],
                        [[7,8,9],
                        [10,11,12]],
                        [[13,14,15],
                        [16,17,18]]])

TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([3, 2, 3])