In [27]:
import numpy as np
import pandas as pd

# DataTypes & Attributes

In [17]:
# Numpy's main datatype is ndarray

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [18]:
type(al)

numpy.ndarray

In [19]:
a2 = np.array([[1,1,3.3], [4, 5,6.5]])

a3 = np.array([[[1,2,3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12],[13, 14,15], [16,17,18]]])

In [20]:
a2

array([[1. , 1. , 3.3],
       [4. , 5. , 6.5]])

In [21]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [24]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [26]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [28]:
# Create a DataFrame from a numpy array
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  1.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [30]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [32]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [36]:
random_array_int = np.random.randint(0, 10, size=(3,5))
random_array_int

array([[0, 5, 5, 3, 0],
       [7, 8, 9, 6, 6],
       [6, 9, 7, 0, 2]])

In [46]:
random_array = np.random.random(size=(5,3))
random_array

array([[0.67708232, 0.07095372, 0.18829659],
       [0.02556764, 0.68076699, 0.65872129],
       [0.78954502, 0.03520976, 0.38349156],
       [0.60249359, 0.87682189, 0.8347549 ],
       [0.54913011, 0.05797209, 0.84778574]])

In [47]:
random_array_rand = np.random.rand(5,3)
random_array_rand

array([[0.80720524, 0.24367539, 0.82352164],
       [0.01412311, 0.47883083, 0.2139049 ],
       [0.17922928, 0.74738307, 0.58914354],
       [0.67280975, 0.18820334, 0.13250068],
       [0.05869102, 0.25660454, 0.75967012]])

In [72]:
# Pseudo=random numbers
np.random.seed(seed=10)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6],
       [4, 3, 0]])

In [53]:
random_array_4.shape

(5, 3)

## Viewing Arrays and Matrices

In [73]:
np.unique(random_array_4)

array([0, 1, 3, 4, 6, 8, 9])

In [74]:
a1[0]

1

In [76]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [78]:
a1

array([1, 2, 3])

In [79]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [80]:
a1 + ones

array([2., 3., 4.])

In [81]:
a1 * ones

array([1., 2., 3.])

In [82]:
a2

array([[1. , 1. , 3.3],
       [4. , 5. , 6.5]])

In [83]:
a1 * a2

array([[ 1. ,  2. ,  9.9],
       [ 4. , 10. , 19.5]])

In [85]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"

a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [86]:
np.square(a2)

array([[ 1.  ,  1.  , 10.89],
       [16.  , 25.  , 42.25]])

In [87]:
np.add(a1, ones)

array([2., 3., 4.])

### Aggregation

Aggregation = performing the same operation on a number of things

In [88]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [89]:
a1

array([1, 2, 3])

In [90]:
np.sum(a1)

6

Use python's methods (`sum()`) on Python dataTypes and use NumPy's methods (`np.sum()`) on NumPy arrays

In [93]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [96]:
massive_array[:10]

array([0.52546705, 0.95608734, 0.17758494, 0.3686681 , 0.74760781,
       0.54068446, 0.3041777 , 0.3870569 , 0.46926334, 0.67714282])

In [98]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

4.22 ms ± 271 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
22.6 µs ± 203 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [99]:
np.mean(a2)

3.466666666666667

In [100]:
np.max(a2)

6.5

In [101]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean

np.std(a2)

2.00138840697041

In [102]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

4.0055555555555555

In [103]:
np.sqrt(np.var(a2))

2.00138840697041