In [3]:
import numpy as np
import pandas as pd

# DataTypes & Attributes

In [4]:
# Numpy's main datatype is ndarray

a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(al)

NameError: name 'al' is not defined

In [6]:
a2 = np.array([[1,1,3.3], [4, 5,6.5]])

a3 = np.array([[[1,2,3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12],[13, 14,15], [16,17,18]]])

In [7]:
a2

array([[1. , 1. , 3.3],
       [4. , 5. , 6.5]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
# Create a DataFrame from a numpy array
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  1.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [13]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [16]:
random_array_int = np.random.randint(0, 10, size=(3,5))
random_array_int

array([[7, 2, 8, 4, 2],
       [8, 9, 0, 1, 6],
       [6, 0, 1, 6, 7]])

In [17]:
random_array = np.random.random(size=(5,3))
random_array

array([[0.80629296, 0.4205459 , 0.09192608],
       [0.07024973, 0.36223738, 0.45374546],
       [0.11585252, 0.15566142, 0.81899914],
       [0.55197798, 0.7280303 , 0.95330227],
       [0.38601517, 0.55920586, 0.07106537]])

In [18]:
random_array_rand = np.random.rand(5,3)
random_array_rand

array([[0.7026558 , 0.89385874, 0.3685703 ],
       [0.3492311 , 0.55134203, 0.61410259],
       [0.30586305, 0.29597757, 0.76041636],
       [0.8657001 , 0.63720669, 0.54040837],
       [0.2474259 , 0.93574085, 0.9732852 ]])

In [19]:
# Pseudo=random numbers
np.random.seed(seed=10)

random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6],
       [4, 3, 0]])

In [20]:
random_array_4.shape

(5, 3)

## Viewing Arrays and Matrices

In [21]:
np.unique(random_array_4)

array([0, 1, 3, 4, 6, 8, 9])

In [22]:
a1[0]

1

In [23]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [24]:
a1

array([1, 2, 3])

In [25]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [26]:
a1 + ones

array([2., 3., 4.])

In [27]:
a1 * ones

array([1., 2., 3.])

In [28]:
a2

array([[1. , 1. , 3.3],
       [4. , 5. , 6.5]])

In [29]:
a1 * a2

array([[ 1. ,  2. ,  9.9],
       [ 4. , 10. , 19.5]])

In [30]:
# How can you reshape a2 to be compatible with a3?
# Search: "How to reshape numpy array"

a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [31]:
np.square(a2)

array([[ 1.  ,  1.  , 10.89],
       [16.  , 25.  , 42.25]])

In [32]:
np.add(a1, ones)

array([2., 3., 4.])

### Aggregation

Aggregation = performing the same operation on a number of things

In [33]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [34]:
a1

array([1, 2, 3])

In [35]:
np.sum(a1)

6

Use python's methods (`sum()`) on Python dataTypes and use NumPy's methods (`np.sum()`) on NumPy arrays

In [36]:
# Creative a massive NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [37]:
massive_array[:10]

array([0.81660184, 0.33607158, 0.89081653, 0.19812181, 0.03061665,
       0.87761494, 0.72743551, 0.54088093, 0.13145815, 0.41366737])

In [38]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

11.4 ms ± 471 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
35 µs ± 3.46 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [39]:
np.mean(a2)

3.466666666666667

In [40]:
np.max(a2)

6.5

In [41]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean

np.std(a2)

2.00138840697041

In [42]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

4.0055555555555555

In [43]:
np.sqrt(np.var(a2))

2.00138840697041

In [44]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])
print(high_var_array, low_var_array)

[   1  100  200  300 4000 5000] [ 2  4  6  8 10]


In [45]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [46]:
np.std(high_var_array), np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

In [47]:
np.mean(high_var_array), np.mean(low_var_array)

(1600.1666666666667, 6.0)